import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Laguna Beach Shirt',
      slug: 'laguna-beach-shirt',
      category: 'Shirts',
      image: '/images/shirt1.png',
      price: 70,
      brand: 'Surfdome',
      rating: 4.8,
      numReviews: 28,
      countInStock: 0,
      description: 'The Coolest Shirt on the Market',
    },
    {
      name: 'Thalia Surf Shirt',
      slug: 'thalia-surf-shirt',
      category: 'Shirts',
      image: '/images/shirt3.png',
      price: 50,
      brand: 'SurfzUp',
      rating: 4.2,
      numReviews: 17,
      countInStock: 15,
      description: 'Blue like the Ocean',
    },
    {
      name: 'Vans White Hoodie',
      slug: 'vans-white-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie1.jpg',
      price: 90,
      brand: 'SurfzUp',
      rating: 4.1,
      numReviews: 14,
      countInStock: 30,
      description: 'Vans up your Look',
    },
    {
      name: 'Surfboards Shirt',
      slug: 'surfboards-shirt',
      category: 'Shirts',
      image: '/images/shirt2.png',
      price: 50,
      brand: 'Surfdome',
      rating: 4.6,
      numReviews: 32,
      countInStock: 25,
      description: 'Surf with Style',
    },
    {
      name: 'Grey Hoodie',
      slug: 'grey-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie2.png',
      price: 90,
      brand: 'Surfdome',
      rating: 4.2,
      numReviews: 12,
      countInStock: 20,
      description: 'Special Quality and Soft Fabric',
    },
    {
      name: 'Thalia Surf Hoodie',
      slug: 'thalia-surf-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie3.png',
      price: 90,
      brand: 'SurfzUp',
      rating: 4.9,
      numReviews: 40,
      countInStock: 32,
      description: 'Best seller amongst Surfers',
    },
  ],
};

export default data;
